### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by AriaMoradi** [AntiMicroX/antimicrox.github.io#5]
Our options for licensing are these(ordered by my liking):
1- CC-BY-SA: https://creativecommons.org/licenses/by-sa/3.0/
2- PDL: https://www.openoffice.org/licenses/PDL.html
3- GFDL: https://www.gnu.org/licenses/fdl-1.3.en.html
4- MIT

**Comment by gombosg** [comment]
Licensing is tricky. Sorry for not looking at this earier.

CC-BY-SA is discouraged for software [even by its creators](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software).

The original AntiMicroX is GPLv3, so **we should choose GPLv3 for this, too**, because we would be reusing content from the original application (Text, man page, images, even maybe source code lines etc.), and GPLv3 is copyleft so if you redistribute GPLv3 content, you have to redistribute it under the same or a more restrictive license.

**Comment by gombosg** [comment]
You can argue that our content reuse is different and falls under 'fair use' clauses but even then I don't see why we couldn't just use GPL which is consistent with the original project.

Do you have any other arguments here?

**Comment by AriaMoradi** [comment]
> Do you have any other arguments here?

On further research because the way vuepress works(It's clear what "source code" is), GPL works better.
Agreed.
